---
- name: "Copy installation files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/rustdesk-install/"
    mode: preserve
  loop: "{{ lookup('fileglob', role_path + '/files/*').split(',') }}"

- name: "Execute installation script"
  ansible.builtin.command:
    chdir: /home/rustdesk-install/
    cmd: /home/rustdesk-install/install-rustdesk.sh