---

- name: "Start and enable rustdesk-hbbr.service"
  ansible.builtin.service:
    name: "rustdesk-hbbr"
    state: started
    enabled: true
    daemon_reload: true

- name: "Start and enable rustdesk-hbbs.service"
  ansible.builtin.service:
    name: "rustdesk-hbbs"
    state: started
    enabled: true
    daemon_reload: true
